//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.WalletsSampleDataSource
{
    using System; 
    using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
    internal class WalletsSampleDataSource { }
#else

    public class WalletsSampleDataSource : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public WalletsSampleDataSource()
        {
            try
            {
                Uri resourceUri = new Uri("ms-appx:/SampleData/WalletsSampleDataSource/WalletsSampleDataSource.xaml", UriKind.RelativeOrAbsolute);
                Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
            }
            catch
            {
            }
        }

        public Wallets Wallets { get; } = new Wallets();

        public Banks Banks { get; } = new Banks();

        public Categories Categories { get; } = new Categories();

        private Category _Category = new Category();

        public Category Category
        {
            get => _Category;

            set
            {
                if (_Category != value)
                {
                    _Category = value;
                    OnPropertyChanged("Category");
                }
            }
        }
    }

    public class Wallets : System.Collections.ObjectModel.ObservableCollection<WalletsItem>
    { 
    }

    public class WalletsItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private Icon _Icon = new Icon();

        public Icon Icon
        {
            get => _Icon;

            set
            {
                if (_Icon != value)
                {
                    _Icon = value;
                    OnPropertyChanged("Icon");
                }
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
    }

    public class Icon : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        private string _Path = string.Empty;

        public string Path
        {
            get => _Path;

            set
            {
                if (_Path != value)
                {
                    _Path = value;
                    OnPropertyChanged("Path");
                }
            }
        }
    }

    public class Banks : System.Collections.ObjectModel.ObservableCollection<BanksItem>
    { 
    }

    public class BanksItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private Icon1 _Icon = new Icon1();

        public Icon1 Icon
        {
            get => _Icon;

            set
            {
                if (_Icon != value)
                {
                    _Icon = value;
                    OnPropertyChanged("Icon");
                }
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
    }

    public class Icon1 : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        private string _Path = string.Empty;

        public string Path
        {
            get => _Path;

            set
            {
                if (_Path != value)
                {
                    _Path = value;
                    OnPropertyChanged("Path");
                }
            }
        }
    }

    public class Categories : System.Collections.ObjectModel.ObservableCollection<CategoriesItem>
    { 
    }

    public class CategoriesItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
    }

    public class Category : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public Wallets1 Wallets { get; } = new Wallets1();

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        private string _ImageUri = string.Empty;

        public string ImageUri
        {
            get => _ImageUri;

            set
            {
                if (_ImageUri != value)
                {
                    _ImageUri = value;
                    OnPropertyChanged("ImageUri");
                }
            }
        }

        private Image _Image = new Image();

        public Image Image
        {
            get => _Image;

            set
            {
                if (_Image != value)
                {
                    _Image = value;
                    OnPropertyChanged("Image");
                }
            }
        }

        public Rules Rules { get; } = new Rules();
    }

    public class Wallets1 : System.Collections.ObjectModel.ObservableCollection<WalletsItem1>
    { 
    }

    public class WalletsItem1 : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        private string _ImageUri = string.Empty;

        public string ImageUri
        {
            get => _ImageUri;

            set
            {
                if (_ImageUri != value)
                {
                    _ImageUri = value;
                    OnPropertyChanged("ImageUri");
                }
            }
        }
    }

    public class Image : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private string _Path = string.Empty;

        public string Path
        {
            get => _Path;

            set
            {
                if (_Path != value)
                {
                    _Path = value;
                    OnPropertyChanged("Path");
                }
            }
        }
    }

    public class RulesItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private double _Id = 0;

        public double Id
        {
            get => _Id;

            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }

        private string _Name = string.Empty;

        public string Name
        {
            get => _Name;

            set
            {
                if (_Name != value)
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        private string _Description = string.Empty;

        public string Description
        {
            get => _Description;

            set
            {
                if (_Description != value)
                {
                    _Description = value;
                    OnPropertyChanged("Description");
                }
            }
        }

        private string _Pattern = string.Empty;

        public string Pattern
        {
            get => _Pattern;

            set
            {
                if (_Pattern != value)
                {
                    _Pattern = value;
                    OnPropertyChanged("Pattern");
                }
            }
        }
    }

    public class Rules : System.Collections.ObjectModel.ObservableCollection<RulesItem>
    { 
    }
#endif
}
